
<div>        
    <img src="..\Week 01\img\R_logo.svg" width="100"/>  
</div>

<div style="line-height:600%;">
    <font color=#1363E1 face="Sriracha" size=8>
            <div align=center>OPERATORS</div>
    </font>    
</div>


<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=justify>
An operator is a symbol that tells the compiler to perform specific <mark>mathematical or logical manipulations</mark>. <ins>R language</ins> is rich in built-in operators and provides following types of operators.
                </div>
    </font>
    <br>
    <font color=black face="Sriracha" size=5>
                <div align=left>
                    Types of Operators:
                </div>
    </font>
    <font color=black face="Candara" size=4>
                <div align=left>
                    <ul>
                        <li>Arithmetic Operators</li>
                        <li>Relational Operators</li>
                        <li>Logical Operators</li>
                        <li>Assignment Operators</li>
                        <li>Miscellaneous Operators</li>
                    </ul>
                </div>
    </font>
</div>

<div>        
    <img src="..\Week 02\img\ope_pre.png" width="400"/>  
</div>


<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Arithmetic Operators</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
Following table shows the arithmetic operators supported by R language. The operators act on <mark>each element of the vector</mark>.
                </div>
    </font>
</div>




<div>        
    <img src="..\Week 02\img\R_arithmetic_operators.png" width="400"/>  
</div>


<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b><mark>+</mark> : Adds Two Vectors</b>
                </div>
    </font>
</div>

In [6]:
v <- c(1, 2, 3)

t <- c(4, 5, 6)

print(v + t)

z <- v + t
print(z)

[1] 5 7 9
[1] 5 7 9


<div>        
    <img src="..\Week 02\img\Add.png" width="150"/>  
</div>

<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b><mark>-</mark> : Subtracts Second Vector From The First</b>
                </div>
    </font>
</div>

In [9]:
v <- c(1, 2, 3)

t <- c(4, 5, 6)

print(v - t)

[1] -3 -3 -3


<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b><mark>*</mark> : Multiplies Both Vectors</b>
                </div>
    </font>
</div>

In [15]:
v <- c(1, 2, 3, NA, 4)

t <- c(4, 5, 6, 7, 8)

print(v * t)

[1]  4 10 18 NA 32


<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b><mark>/</mark> : Divide The First Vector With The Second</b>
                </div>
    </font>
</div>

In [16]:
v <- c(1, 2, 3)

t <- c(4, 5, 6)

print(v / t)

[1] 0.25 0.40 0.50


<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b><mark>%%</mark> : Give The Remainder Of The First Vector With The Second</b>
                </div>
    </font>
</div>

In [19]:
v <- c(10, 20, 34)

t <- c(4, 5, 6)

print(v %% t)

[1] 79
[1] 2 0 4


<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b><mark>%/%</mark>: The Result Of Division Of First Vector With Second (Quotient)</b>
                </div>
    </font>
</div>

In [7]:
v <- c(10, 20, 34)

t <- c(4, 5, 6)

print(v %/%t)

[1] 2 4 5


<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b><mark>^</mark> : The First Vector Raised To The Exponent Of Second Vector</b>
                </div>
    </font>
</div>

In [18]:
v <- c(1, 2, 3)

t <- c(4, 5, 6)

print(v ^ t)

[1]   1  32 729


<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Relational Operators</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
Following table shows the <mark>relational operators</mark> supported by R language. Each element of the first vector is <mark>compared</mark> with the corresponding element of the second vector. The result of comparison is a <mark>Boolean value</mark>.
                </div>
    </font>
</div>





<div>        
    <img src="..\Week 02\img\R_rel_ope.png" width="400"/>  
</div>



<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b><mark>></mark> : Checks If Each Element Of The First Vector Is Greater Than The Corresponding Element Of The Second Vector</b>
                </div>
    </font>
</div>

In [21]:
v <- c(10, 2, 3)

t <- c(4, 5, 3)

print(v > t)

[1]  TRUE FALSE FALSE


<div>        
    <img src="..\Week 02\img\greaterThan.png" width="150"/>  
</div>

<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
                    <b><mark><</mark> : Checks If Each Element Of The First Vector Is Less Than The Corresponding Element Of The Second Vector</b>
                </div>
    </font>
</div>

In [22]:
v <- c(10, 2, 3)

t <- c(4, 5, 3)

print(v < t)

[1] FALSE  TRUE FALSE



<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
                    <b><mark>>=</mark> : Checks If Each Element Of The First Vector Is Greater Than Or Equal To The Corresponding Element Of The Second Vector</b>
                </div>
    </font>
</div>

In [23]:
v <- c(10, 2, 3)

t <- c(4, 5, 3)

print(v >= t)

[1]  TRUE FALSE  TRUE



<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
                    <b><mark><=</mark> : Checks If Each Element Of The First Vector Is Less Than Or Equal To The Corresponding Element Of The Second Vector</b>
                </div>
    </font>
</div>

In [6]:
v <- c(10, 2, 3)

t <- c(4, 5, 3)

print(v <= t)

[1] FALSE  TRUE  TRUE



<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
                    <b><mark>==</mark> : Checks If Each Element Of The First Vector Is Equal To The Corresponding Element Of The Second Vector</b>
                </div>
    </font>
</div>

In [17]:
v <- c(10, 2, 3)

t <- c(4, 5, 3)

print(v == t)

[1] FALSE FALSE  TRUE



<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
                    <b><mark>!=</mark> : Checks If Each Element Of The First Vector Is Unequal To The Corresponding Element Of The Second Vector</b>
                </div>
    </font>
</div>

In [7]:
v <- c(10, 2, 3)

t <- c(4, 5, 3)

print(v != t)

[1]  TRUE  TRUE FALSE



<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Logical Operators</div>
    </font>
</div>


<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
Following table shows the <mark>Logical Operators</mark> supported by R language. It is applicable only to <mark>vectors of type logical, numeric or complex</mark>. <b>All numbers greater than 1 are considered as logical value TRUE</b>.

Each element of the first vector is compared with the corresponding element of the second vector. The result of comparison is a <mark>Boolean Value</mark>.
                </div>
    </font>
</div>










<div>        
    <img src="..\Week 02\img\R_log_ope.png" width="400"/>  
</div>


<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
                    <b><mark>&</mark> : It is called <ins>Element-wise Logical AND operator</ins>. It combines each element of the first vector with the corresponding element of the second vector and gives a output <ins>TRUE if both the elements are TRUE</ins>.</b>
                </div>
    </font>
</div>

In [9]:
v <- c(-1, 1, 0, TRUE, 2+3i)

t <- c(4, 1, 5, FALSE, 3+9i)

print(v & t)

[1]  TRUE  TRUE FALSE FALSE  TRUE


<div>        
    <img src="..\Week 02\img\and.png" width="500"/>  
</div>

| CONDITION 1 | CONDITION 2 | CONDITION 1 && CONDITION 2 |
| :--------------:| :--------------: | :------: |
| TRUE | TRUE | TRUE |
| TRUE | FALSE | FALSE |
| FALSE | TRUE | FALSE |
| FALSE | FALSE | FALSE |


<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
                    <b><mark>|</mark> : It is called <ins>Element-wise Logical OR operator</ins>. It combines each element of the first vector with the corresponding element of the second vector and gives a <ins>output TRUE if one the elements is TRUE</ins>.</b>
                </div>
    </font>
</div>


In [10]:
v <- c(-1, 1, 0, TRUE, 0)

t <- c(4, 1, 5, FALSE, FALSE)

print(v | t)

[1]  TRUE  TRUE  TRUE  TRUE FALSE


<div>        
    <img src="..\Week 02\img\or.png" width="500"/>  
</div>

| CONDITION 1 | CONDITION 2 | CONDITION 1 or CONDITION 2 |
| :--------------:| :--------------: | :------: |
| TRUE | TRUE | TRUE |
| TRUE | FALSE | TRUE |
| FALSE | TRUE | TRUE |
| FALSE | FALSE | FALSE |


<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
                    <b><mark>!</mark> : It is called <ins>Logical NOT Operator</ins>. Takes each element of the vector and gives the opposite logical value.</b>
                </div>
    </font>
</div>

In [7]:
v <- c(-1, 1, 0, TRUE, FALSE)

print(!v)

[1] FALSE FALSE  TRUE FALSE FALSE  TRUE


<div>        
    <img src="..\Week 02\img\not.png" width="500"/>  
</div>

| First Element | Output |
| :--------------:| :--------------: |
| TRUE | FALSE |
| FALSE | TRUE |

>The logical operator `&&` and `||` considers only the first element of the vectors and give a vector of `single element as output`.


<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
                    <b><mark>&&</mark> : Called <ins>Logical AND Operator</ins>. Takes first element of both the vectors and gives the TRUE only if both are TRUE.</b>
                </div>
    </font>
</div>

In [24]:
v <- c(-1, 1, 0, TRUE, 0)

t <- c(4, 1, 5, FALSE, FALSE)

print(v & t)

print(v && t)

[1]  TRUE  TRUE FALSE FALSE FALSE
[1] TRUE


<div>        
    <img src="..\Week 02\img\andand.png" width="500"/>  
</div>


<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
                    <b><mark>||</mark> : Called <ins>Logical OR Operator</ins>. Takes first element of both the vectors and gives the TRUE if one of them is TRUE.</b>
                </div>
    </font>
</div>

In [17]:
v <- c(0, 0, 1, FALSE, 0)

t <- c(4, 0, 5, FALSE, FALSE)

print(v | t)

print(v || t)

[1]  TRUE FALSE  TRUE FALSE FALSE
[1] TRUE


<div>        
    <img src="..\Week 02\img\oror.png" width="500"/>  
</div>



<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Assignment Operators</div>
    </font>
</div>


<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
These operators are used to assign values to vectors.</div>
    </font>
</div>

<div>        
    <img src="..\Week 02\img\assi_ope.png" width="500"/>  
</div>







<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
Leftwards Assignment
                </div>
    </font>
</div>

In [26]:
v1 <- c(3, 1, TRUE, 2+3i)
v3 = c(3, 1, TRUE, 2+3i)
v2 <<- c(3, 1, TRUE, 2+3i)

print(v1)
print(v2)
print(v3)

[1] 3 1 1
[1] 3+0i 1+0i 1+0i 2+3i
[1] 3+0i 1+0i 1+0i 2+3i


<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
Rightwards Assignment
                </div>
    </font>
</div>

In [27]:
c(3, 1, TRUE, 2+3i) -> v1
c(3, 1, TRUE, 2+3i) ->> v2

print(v1)
print(v2)

[1] 3+0i 1+0i 1+0i 2+3i
[1] 3+0i 1+0i 1+0i 2+3i


<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Miscellaneous Operators</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
These operators are used to for specific purpose and not general mathematical or logical computation.</div>
    </font>
</div>







<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
                    <b><mark>:</mark> : <ins>Colon Operator</ins>. It creates the <ins>series of numbers in sequence</ins> for a vector.</b>
                </div>
    </font>
</div>

In [34]:
v <- 1:4

print(v) 

[1] 1 2 3 4



<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
                    <b><mark>%in%</mark> : This operator is used to <ins>identify if an element belongs to a vectorColon Operator</ins>.</b>
                </div>
    </font>
</div>

In [35]:
v1 <- 8

v2 <- 12

t <- 1:10

print(t)

print(v1 %in% t) 

print(v2 %in% t) 

 [1]  1  2  3  4  5  6  7  8  9 10
[1] TRUE
[1] FALSE



<div style="line-height:200%;">
    <font color=#076F9A  face="Candara" size=4>
                <div align=left>
                    <b><mark>%*%</mark> : This operator is used to <ins>multiply a matrix with its transpose</ins>.</b>
                </div>
    </font>
</div>

<div style="line-height:100%;">
    <font color=black face="Britannic" size=6>
                <div align=left></div>
    </font>
</div>

In [37]:
M = matrix(data = c(2, 6, 5, 1, 10, 4),
           nrow = 2,
           ncol = 3,
           byrow = TRUE)

print("M:")
print(M)

t1 = M %*% t(M)
print("M %*% t(M):")
print(t1)

mm = 2 * M

t2 = M * mm
print("M * t(M):")
print(t2)

[1] "M:"
     [,1] [,2] [,3]
[1,]    2    6    5
[2,]    1   10    4
[1] "M %*% t(M):"
     [,1] [,2]
[1,]   65   82
[2,]   82  117
[1] "M * t(M):"
     [,1] [,2] [,3]
[1,]    8   72   50
[2,]    2  200   32
