
<div>        
    <img src="..\Week 01\img\R_logo.svg" width="100"/>  
</div>

<div style="line-height:600%;">
    <font color=#1363E1 face="Sriracha" size=8>
            <div align=center>R Data Structure</div>
    </font>    
</div>

<div>        
    <img src="..\Week 04\img\DataSt.png" width="600"/>  
</div>

<div style="line-height:600%;">
    <font color=#1363E1 face="Sriracha" size=8>
            <div align=center>Matrices</div>
    </font>    
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
Matrices are the R objects in which the elements are arranged in a <mark>Two-dimensional Rectangular Layout</mark>. <b>They contain elements of the same atomic types</b>. Though we can create a matrix containing only characters or only logical values, they are not of much use. We use matrices containing numeric elements to be used in mathematical calculations.

A <b>Matrix</b> is created using the <mark>matrix() function</mark>.
                </div>
    </font>
</div>





<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    <b>Syntax:</b>
The basic syntax for creating a matrix in R is:
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    Following is the description of the parameters used:
<ul>
    <li><b>data:</b> is the input vector which becomes the data elements of the matrix.</li>
  <li><b>nrow:</b> is the number of rows to be created.</li>
  <li><b>ncol:</b> is the number of columns to be created.</li>
    <li><b>byrow:</b> 
 is a logical clue. If TRUE then the input vector elements are arranged by row.</li>
    <li><b>dimname:</b> is the names assigned to the rows and columns.</li>
</ul>
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b>Example:</b>
                </div>
    </font>
</div>

In [2]:
# Elements are arranged sequentially by row.
M <- matrix(data = c(3:14), nrow = 4, byrow = TRUE)
print(M)

# Elements are arranged sequentially by column.
N <- matrix(data = c(3:14), nrow = 4, byrow = FALSE)
print(N)

# Define the column and row names.
rownames = c("row1", "row2", "row3", "row4")
colnames = c("col1", "col2", "col3")

P <- matrix(data = c(3:14),
            nrow = 4, 
            byrow = TRUE,
            dimnames = list(rownames, colnames))
print(P)

     [,1] [,2] [,3]
[1,]    3    4    5
[2,]    6    7    8
[3,]    9   10   11
[4,]   12   13   14
     [,1] [,2] [,3]
[1,]    3    7   11
[2,]    4    8   12
[3,]    5    9   13
[4,]    6   10   14
     col1 col2 col3
row1    3    4    5
row2    6    7    8
row3    9   10   11
row4   12   13   14


<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Accessing Elements of a Matrix</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    Elements of a matrix can be accessed by using the column and row index of the element. We consider the matrix P above to find the specific elements below:
                </div>
    </font>
</div>

In [3]:
# Define the column and row names.
rownames = c("row1", "row2", "row3", "row4")
colnames = c("col1", "col2", "col3")

# Create the matrix.
P <- matrix(data = c(3:14),
            nrow = 4,
            byrow = TRUE, 
            dimnames = list(rownames, colnames))

# Access the element at 3rd column and 1st row.
print(P[1,3])

# Access the element at 2nd column and 4th row.
print(P[4,2])

# Access only the  2nd row.
print(P[2,])

# Access only the 3rd column.
print(P[,3])

[1] 5
[1] 13
col1 col2 col3 
   6    7    8 
row1 row2 row3 row4 
   5    8   11   14 


<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Matrix Computations</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    Various mathematical operations are performed on the matrices using the R operators. The result of the operation is also a matrix.

The dimensions (number of rows and columns) should be same for the matrices involved in the operation.
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    <b>Matrix Addition and Subtraction:</b>
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b>Example:</b>
                </div>
    </font>
</div>

In [4]:
# Create two 2x3 matrices.
matrix1 <- matrix(data = c(3, 9, -1, 4, 2, 6), nrow = 2)
print(matrix1)

matrix2 <- matrix(data = c(5, 2, 0, 9, 3, -4), nrow = 2)
print(matrix2)

# Add the matrices.
result <- matrix1 + matrix2
cat("Result of addition:","\n")
print(result)

# Subtract the mat-rices
result <- matrix1  matrix2
cat("Result of subtraction:","\n")
print(result)

     [,1] [,2] [,3]
[1,]    3   -1    2
[2,]    9    4    6
     [,1] [,2] [,3]
[1,]    5    0    3
[2,]    2    9   -4
Result of addition 
     [,1] [,2] [,3]
[1,]    8   -1    5
[2,]   11   13    2
Result of subtraction 
     [,1] [,2] [,3]
[1,]   -2   -1   -1
[2,]    7   -5   10


<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    <b>Matrix Addition and Subtraction:</b>
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b>Example:</b>
                </div>
    </font>
</div>

In [5]:
# Create two 2x3 matrices.
matrix1 <- matrix(data = c(3, 9, -1, 4, 2, 6), nrow = 2)
print(matrix1)

matrix2 <- matrix(data = c(5, 2, 0, 9, 3, 4), nrow = 2)
print(matrix2)

# Multiply the matrices.
result <- matrix1 * matrix2
cat("Result of multiplication","\n")
print(result)

# Divide the matrices
result <- matrix1 / matrix2
cat("Result of division","\n")
print(result)

     [,1] [,2] [,3]
[1,]    3   -1    2
[2,]    9    4    6
     [,1] [,2] [,3]
[1,]    5    0    3
[2,]    2    9    4
Result of multiplication 
     [,1] [,2] [,3]
[1,]   15    0    6
[2,]   18   36   24
Result of division 
     [,1]      [,2]      [,3]
[1,]  0.6      -Inf 0.6666667
[2,]  4.5 0.4444444 1.5000000



<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Create R Matrix using cbind and rbind</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b>Example:</b>
                </div>
    </font>
</div>

In [2]:
A <- c(1, 2, 3) 
B <- c(10, 20, 30)

X <- cbind(A, B)
print(X)

cat("\n")

Y <- rbind(A, B)
print(Y)

cat("\n")

Z <- cbind(X, c(100, 200, 300))
print(Z)

cat("\n")

Z <- rbind(Y, C = c(100, 200, 300))
print(Z)

     A  B
[1,] 1 10
[2,] 2 20
[3,] 3 30

  [,1] [,2] [,3]
A    1    2    3
B   10   20   30

     A  B    
[1,] 1 10 100
[2,] 2 20 200
[3,] 3 30 300



Warning message in rbind(Y, C = c(100, 200)):
"number of columns of result is not a multiple of vector length (arg 2)"

  [,1] [,2] [,3]
A    1    2    3
B   10   20   30
C  100  200  100



<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Matrix with Recycling Elements</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b>Example:</b>
                </div>
    </font>
</div>

In [14]:
# R Create Matrix

A <- matrix(c(44: 46), nrow = 3, ncol = 3)
print(A)

B <- matrix(c(44: 46), nrow = 3, ncol = 3, byrow = TRUE)
print(B)

     [,1] [,2] [,3]
[1,]   44   44   44
[2,]   45   45   45
[3,]   46   46   46
     [,1] [,2] [,3]
[1,]   44   45   46
[2,]   44   45   46
[3,]   44   45   46



<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Tips and Tricks</div>
    </font>
</div>

In [4]:
# Data Type and Dimensions of Matrix in R

A <- matrix(data = c(1:12),
            nrow = 3, 
            ncol = 4, 
            byrow = TRUE)
print(A)

class(A)

dim(A)

nrow(A)

ncol(A)

t(A)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12


[1] "matrix"

[1] 3 4

[1] 3

[1] 4

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

In [5]:
# Accessing R Matrix Elements Subset

A <- matrix(data = c(1:12),
            nrow = 3, 
            ncol = 4,
            byrow = TRUE)
print(A)
cat("\n")

# Access the elements at 1st, 3rd row and 2nd, 4th column.
print(A[c(1, 2), c(3, 4)])
cat("\n")

# Access All the element at 2nd and 3rd row.
print(A[c(2, 3), ])
cat("\n")

# Access All the element at 1st and 4th Column.
print(A[ , c(1, 4)])
cat("\n")

# Access All the element except 2nd row.
print(A[-2, ])
cat("\n")

# Access All the element except 2nd row and 3rd Columm.
print(A[-2, -3])
cat("\n")

# Access All the element except 3rd and 4th Columm.
print(A[, c(-2, -4)])

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12

     [,1] [,2]
[1,]    3    4
[2,]    7    8

     [,1] [,2] [,3] [,4]
[1,]    5    6    7    8
[2,]    9   10   11   12

     [,1] [,2]
[1,]    1    4
[2,]    5    8
[3,]    9   12

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    9   10   11   12

     [,1] [,2] [,3]
[1,]    1    2    4
[2,]    9   10   12

     [,1] [,2]
[1,]    1    3
[2,]    5    7
[3,]    9   11


In [20]:
# Accessing R Matrix Elements using Boolean Vector

A <- matrix(data = c(1:12),
            nrow = 3,
            ncol = 4, 
            byrow = TRUE)
print(A)
cat("\n")

# Access the elements at 1st, 3rd row and 2nd, 4th column.
print(A[c(TRUE, FALSE, TRUE), c(FALSE, TRUE, FALSE, TRUE)])
cat("\n")

# Access All the element at 1ST AND 2nd row.
print(A[c(TRUE, TRUE, FALSE), ])
cat("\n")

# Access All the element at 1st and 4th Column.
print(A[ , c(FALSE, TRUE)])
cat("\n")

# Access the elements at 1st, 2nd row and 2nd, 4th column.
print(A[c(1, 2), c(FALSE, TRUE, FALSE, TRUE)])

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10   11   12

     [,1] [,2]
[1,]    2    4
[2,]   10   12

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8

     [,1] [,2]
[1,]    2    4
[2,]    6    8
[3,]   10   12

     [,1] [,2]
[1,]    2    4
[2,]    6    8


In [22]:
# Accessing R Matrix Elements using Char Index

# Defining Row names and Column names of Matrix in R
row.names <- c("Row1", "Row2", "Row3")
column.names <-c("Col1", "Col2", "Col3", "Col4")

B <- matrix(data = c(1:12),
            nrow = 3, 
            dimnames = list(row.names, column.names))
print(B)
cat("\n")

# Access the elements at 1st row and 3rd Column.
print(B["Row1", "Col3"])
cat("\n")

# Access only the 2nd row.
print(B["Row2",])
cat("\n")

# Access only the 4th column.
print(B[, "Col4"])
cat("\n")

# Access the elements at 2nd row and 2, 3, 4th Column.
print(B["Row2", 2:4])
cat("\n")

# Access the elements at 1st, 3rd row and 1, 2, 3rd Column.
print(B[c("Row1", "Row2"), 2:4])

     Col1 Col2 Col3 Col4
Row1    1    4    7   10
Row2    2    5    8   11
Row3    3    6    9   12

[1] 7

Col1 Col2 Col3 Col4 
   2    5    8   11 

Row1 Row2 Row3 
  10   11   12 

Col2 Col3 Col4 
   5    8   11 

     Col2 Col3 Col4
Row1    4    7   10
Row2    5    8   11


In [11]:
# Modifying Matrix in R Programming

A <- matrix(data = c(1:9),
            nrow = 3,
            ncol = 3)
print(A)
cat("\n")

A[2, 2] <- 100
print(A)
cat("\n")

A[A < 5] <- NA
print(A)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2  100    8
[3,]    3    6    9

     [,1] [,2] [,3]
[1,]   NA   NA    7
[2,]   NA  100    8
[3,]   NA    6    9


In [13]:
# These names can be accessed or changed with two helpful functions
# colnames() and rownames().

A <- matrix(data = c(1:9),
            nrow = 3,
            ncol = 3)
print(A)
cat("\n")

print(colnames(A))
cat("\n")

print(rownames(A))
cat("\n")

colnames(A) <- c("1", "2", "3")
rownames(A) <- c("A", "B", "C")
print(A)
cat("\n")

print(colnames(A))
cat("\n")

print(rownames(A))

rownames(A) <- NULL

print(A)


     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

NULL

NULL

  1 2 3
A 1 4 7
B 2 5 8
C 3 6 9

[1] "1" "2" "3"

[1] "A" "B" "C"
     1 2 3
[1,] 1 4 7
[2,] 2 5 8
[3,] 3 6 9


In [36]:
A <- matrix(data = 1:6, nrow = 2)
print(A)
cat("\n")

dim(A)
cat("\n")

dim(A) <- c(3, 2)
print(A)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6



[1] 2 3


     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6
