
<div>        
    <img src="..\Week 01\img\R_logo.svg" width="100"/>  
</div>

<div style="line-height:600%;">
    <font color=#1363E1 face="Sriracha" size=8>
            <div align=center>R Data Structure</div>
    </font>    
</div>

<div>        
    <img src="..\Week 04\img\DataSt.png" width="600"/>  
</div>

<div style="line-height:600%;">
    <font color=#1363E1 face="Sriracha" size=8>
            <div align=center>Arrays</div>
    </font>    
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
<mark>Arrays</mark> are the R data objects which can store data in more than two dimensions. For example, If we create an array of dimension (2, 3, 4) then it creates 4 rectangular matrices each with 2 rows and 3 columns. <mark>Arrays can store only data type</mark>.

An array is created using the <mark>array() function</mark>. It takes vectors as input and uses the values in the dim parameter to create an array.
                </div>
    </font>
</div>





<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    <b>Syntax:</b>
The basic syntax of the Array in R Programming language is as shown below::
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    Following is the description of the parameters used:
<ul>
    <li><b>data:</b> is the input vector which becomes the data elements of the array.</li>
  <li><b>row_Size:</b> Number of Row elements an array can store. For example, Row_Size =5 then each matrix in an array will have 5 rows.</li>
  <li><b>column_Size:</b> Number of Column elements an array can store. For example, Column_Size = 6 then each matrix in an array will have 6 Columns.</li>
    <li><b>Matrices:</b> 
 It will decide the number of Matrices an array can accept. Array in R is always a Multi Dimensional, it means more than 1 matrix with rows and columns.</li>
    <li><b>dimname:</b> It is used to change the default Row, Column, Matrices names to more meaningful names.</li>
</ul>
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b>Example:</b>
                </div>
    </font>
</div>

In [4]:
# Create two vectors of different lengths.
vector1 <- c(5, 9, 3)
vector2 <- c(10, 11, 12, 13, 14, 15)

# Take these vectors as input to the array.
result <- array(data = c(vector1, vector2), dim = c(3,3,1))
print(result)

print("-------------------------------------------------------")

result <- array(data = c(vector1, vector2), dim = c(3,3,2))
print(result)

, , 1

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15

[1] "-------------------------------------------------------"
, , 1

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15

, , 2

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15



<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Naming Columns and Rows</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    We can give names to the rows, columns and matrices in the array by using the <mark>dimnames</mark> parameter.:
                </div>
    </font>
</div>

In [5]:
column.names <- c("Lon1", "Lon2", "Lon3")
row.names <- c("Lat1", "Lat2", "Lat3")
matrix.names <- c("Day1", "Day2")

result <- array(data = 1:18,
                dim = c(3, 3, 2),
                dimnames = list(row.names, column.names, matrix.names))
print(result)

result[, "Lon3",]

, , Day1

     Lon1 Lon2 Lon3
Lat1    1    4    7
Lat2    2    5    8
Lat3    3    6    9

, , Day2

     Lon1 Lon2 Lon3
Lat1   10   13   16
Lat2   11   14   17
Lat3   12   15   18



Day1 Day2
Lat1 7    16  
Lat2 8    17  
Lat3 9    18

<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Accessing Array Elements</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b>Example:</b>
                </div>
    </font>
</div>

In [10]:
column.names <- c("COL1", "COL2", "COL3")
row.names <- c("ROW1", "ROW2", "ROW3")
matrix.names <- c("Matrix1", "Matrix2")

result <- array(data = 1:18,
                dim = c(3, 3, 2),
                dimnames = list(row.names, column.names, matrix.names))
print(result)
cat("\n")

# Print the third row of the second matrix of the array.
print(result[3,,2])
cat("\n")

# Print the element in the 1st row and 3rd column of the 1st matrix.
print(result[1,3,1])
cat("\n")

# Print the 2nd Matrix.
print(result[,,2])

, , Matrix1

     COL1 COL2 COL3
ROW1    1    4    7
ROW2    2    5    8
ROW3    3    6    9

, , Matrix2

     COL1 COL2 COL3
ROW1   10   13   16
ROW2   11   14   17
ROW3   12   15   18


COL1 COL2 COL3 
  12   15   18 

[1] 7

     COL1 COL2 COL3
ROW1   10   13   16
ROW2   11   14   17
ROW3   12   15   18



<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Manipulating Array Elements</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    As array is made up matrices in multiple dimensions, the operations on elements of array are carried out by accessing elements of the matrices:
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b>Example:</b>
                </div>
    </font>
</div>

In [12]:
column.names <- c("COL1", "COL2", "COL3")
row.names <- c("ROW1", "ROW2", "ROW3")
matrix.names <- c("Matrix1", "Matrix2")

array1 <- array(data = 1:18,
                dim = c(3, 3, 2),
                dimnames = list(row.names, column.names, matrix.names))
print(array1)
cat("\n")

column.names <- c("COL1", "COL2", "COL3")
row.names <- c("ROW1", "ROW2", "ROW3")
matrix.names <- c("Matrix1", "Matrix2")

array2 <- array(data = 19:36,
                dim = c(3, 3, 2),
                dimnames = list(row.names, column.names, matrix.names))
print(array2)
cat("\n")

# create matrices from these arrays.
matrix1 <- array1[,,2]
matrix2 <- array2[,,2]

# Add the matrices.
result <- matrix1 + matrix2
print(result)

, , Matrix1

     COL1 COL2 COL3
ROW1    1    4    7
ROW2    2    5    8
ROW3    3    6    9

, , Matrix2

     COL1 COL2 COL3
ROW1   10   13   16
ROW2   11   14   17
ROW3   12   15   18


, , Matrix1

     COL1 COL2 COL3
ROW1   19   22   25
ROW2   20   23   26
ROW3   21   24   27

, , Matrix2

     COL1 COL2 COL3
ROW1   28   31   34
ROW2   29   32   35
ROW3   30   33   36


     COL1 COL2 COL3
ROW1   38   44   50
ROW2   40   46   52
ROW3   42   48   54



<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Calculations Across Array Elements</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    We can do calculations across the elements in an array using the <mark>apply() function</mark>:
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    <b>Syntax:</b>
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    Following is the description of the parameters used:
<ul>
    <li><b>x:</b> is an array.</li>
  <li><b>margin:</b> is the name of the data set used</li>
  <li><b>fun:</b> is the function to be applied across the elements of the array.</li>
</ul>
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b>Example:</b>
                </div>
    </font>
</div>

In [8]:
column.names <- c("COL1", "COL2", "COL3")
row.names <- c("ROW1", "ROW2", "ROW3")
matrix.names <- c("Matrix1", "Matrix2")

array1 <- array(data = 1:18,
                dim = c(3, 3, 2),
                dimnames = list(row.names, column.names, matrix.names))
print(array1)
cat("\n")

# Use apply to calculate the sum of the rows across all the matrices.
result <- apply(X = array1,
                MARGIN = c(3),
                FUN = mean)
print(result)

, , Matrix1

     COL1 COL2 COL3
ROW1    1    4    7
ROW2    2    5    8
ROW3    3    6    9

, , Matrix2

     COL1 COL2 COL3
ROW1   10   13   16
ROW2   11   14   17
ROW3   12   15   18


Matrix1 Matrix2 
      5      14 



<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Tips and Tricks</div>
    </font>
</div>

In [15]:
# Data Type and Dimensions of Matrix in R

column.names <- c("COL1", "COL2", "COL3")
row.names <- c("ROW1", "ROW2", "ROW3")
matrix.names <- c("Matrix1", "Matrix2")

array1 <- array(data = 1:18,
                dim = c(3, 3, 2),
                dimnames = list(row.names, column.names, matrix.names))
print(array1)
cat("\n")

class(array1)

dim(array1)

nrow(array1)

ncol(array1)

, , Matrix1

     COL1 COL2 COL3
ROW1    1    4    7
ROW2    2    5    8
ROW3    3    6    9

, , Matrix2

     COL1 COL2 COL3
ROW1   10   13   16
ROW2   11   14   17
ROW3   12   15   18




[1] "array"

[1] 3 3 2

[1] 3

[1] 3