
<div>        
    <img src="..\Week 01\img\R_logo.svg" width="100"/>  
</div>

<div style="line-height:600%;">
    <font color=#1363E1 face="Sriracha" size=8>
            <div align=center>R Data Structure</div>
    </font>    
</div>

<div>        
    <img src="..\Week 04\img\DataSt.png" width="600"/>  
</div>

<div style="line-height:600%;">
    <font color=#1363E1 face="Sriracha" size=8>
            <div align=center>Lists</div>
    </font>    
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
<mark>Lists</mark> are the R objects which contain elements of different types like: <b>numbers, strings, vectors and another list inside it</b>. A list can also contain a <b>matrix or a function</b> as its elements. List is created using <mark>list() function</mark>.
                </div>
    </font>
</div>





<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Creating a List</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    Following is an example to create a list containing strings, numbers, vectors and a logical values:
                </div>
    </font>
</div>

In [1]:
# Create a list containing strings, numbers, vectors and a logical values.
list_data <- list("Red", "Green", c(21,32,11), TRUE, 51.23, 119.1)
print(list_data)

[[1]]
[1] "Red"

[[2]]
[1] "Green"

[[3]]
[1] 21 32 11

[[4]]
[1] TRUE

[[5]]
[1] 51.23

[[6]]
[1] 119.1



<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Naming List Elements</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    The list elements can be given names and they can be accessed using these names:
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b>Example:</b>
                </div>
    </font>
</div>

In [20]:
# Create Named List in R Programming

list.data <- list("Company" = "Tutorial Gateway",
                  "Flag" = TRUE,
                  "prod" = c(10, 20, 30),
                  "val" = 95,
                  "sale" = 105.61)
print(list.data)

$Company
[1] "Tutorial Gateway"

$Flag
[1] TRUE

$prod
[1] 10 20 30

$val
[1] 95

$sale
[1] 105.61



In [2]:
# Create a list containing a vector, a matrix and a list.
list_data <- list(c("Jan", "Feb", "Mar"),
                  matrix(data = c(3, 9, 5, 1, -2, 8), nrow = 2),
                  list("green", 12.3))

# Give names to the elements in the list.
names(list_data) <- c("1st Quarter", "A_Matrix", "A Inner list")

# Show the list.
print(list_data)

$`1st Quarter`
[1] "Jan" "Feb" "Mar"

$A_Matrix
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

$`A Inner list`
$`A Inner list`[[1]]
[1] "green"

$`A Inner list`[[2]]
[1] 12.3




In [9]:
# Create a list containing a vector, a matrix and a list.
list_data <- list(c("Jan", "Feb", "Mar"),
                  matrix(data = c(3, 9, 5, 1, -2, 8), nrow = 2),
                  list("green", 12.3))

# Give names to the elements in the list.
names(list_data) <- c("1st Quarter", "A_Matrix", "A Inner list")

names(list_data$"A Inner list") <- c("color", "number")

# Show the list.
print(list_data)

$`1st Quarter`
[1] "Jan" "Feb" "Mar"

$A_Matrix
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

$`A Inner list`
$`A Inner list`$color
[1] "green"

$`A Inner list`$number
[1] 12.3





<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Accessing List Elements</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    Elements of the list can be accessed by the index of the element in the list. In case of named lists it can also be accessed using the names:
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b>Example:</b>
                </div>
    </font>
</div>

In [12]:
# Create a list containing a vector, a matrix and a list.
list_data <- list(c("Jan", "Feb", "Mar"),
                  matrix(data = c(3, 9, 5, 1, -2, 8), nrow = 2),
                  list("green", 12.3))

# Give names to the elements in the list.
names(list_data) <- c("1st Quarter", "A_Matrix", "A Inner list")

# Access the first element of the list.
print(list_data[1])
cat("=======================================","\n")

# Access the thrid element. As it is also a list, all its elements will be printed.
print(list_data[3])
cat("=======================================","\n")

# Access the list element using the name of the element.
print(list_data$A_Matrix)
cat("=======================================","\n")

print(list_data$`A Inner list`)

$`1st Quarter`
[1] "Jan" "Feb" "Mar"

$`A Inner list`
$`A Inner list`[[1]]
[1] "green"

$`A Inner list`[[2]]
[1] 12.3


     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8
[[1]]
[1] "green"

[[2]]
[1] 12.3



In [ ]:
# Accessing R List Elements

vect.x <- c(10, 30, 50, 70)
vect.y <- c("India", "Russia", "Japan", "UK", "China", "USA") 

list.data <- list(vect.x, vect.y)
names(list.data) <- c("Numeric_Vector", "Country") 

matrix.A <- matrix(data = c(1:12), nrow = 3, ncol = 4)
vect.z <- c(55, 75, 25, 105, 125)

list.mixed <- list(matrix.A,
                   list.data,
                   vect.z, 
                   "Tutorial Gateway")

names(list.mixed) <- c("Numeric_Matrix",
                       "Nested_List",
                       "Random_vector",
                       "Company")
print(list.mixed)

# Accessing Vector.z Elements
print(list.mixed$Random_vector)

# Accessing Vector.z Elements
print(list.mixed$Numeric_Matrix)

# Accessing Nested List Elements
print(list.mixed$Nested_List)

In [22]:
# Accessing R List Elements

vect.a <- c(10.25, 30.75, 20.45, 40.85)
vect.b <- c("India", "Japan", "Russia", "China", "USA") 
vect.c <- c(50, 75, 25, 100, 125)

A <- matrix(data = c(1:12), nrow = 3, ncol = 4)

list.data <- list(A,
                  vect.a,
                  "Tutorial Gateway",
                  vect.b,
                  95,
                  vect.c )
print(list.data)
print("============================================")

# Accessing List Element using Boolean Vector
print(list.data[c(FALSE, FALSE, TRUE, FALSE, TRUE, TRUE)])
print("============================================")

# Accessing All Element except 1
print(list.data[-1])
print("============================================")

# Accessing All Element except 4
print(list.data[-4])
print("============================================")

# Accessing All Element except 1 and 6th element
print(list.data[c(-1, -6)])

[[1]]
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

[[2]]
[1] 10.25 30.75 20.45 40.85

[[3]]
[1] "Tutorial Gateway"

[[4]]
[1] "India"  "Japan"  "Russia" "China"  "USA"   

[[5]]
[1] 95

[[6]]
[1]  50  75  25 100 125

[1] "============================================"
[[1]]
[1] "Tutorial Gateway"

[[2]]
[1] 95

[[3]]
[1]  50  75  25 100 125

[1] "============================================"
[[1]]
[1] 10.25 30.75 20.45 40.85

[[2]]
[1] "Tutorial Gateway"

[[3]]
[1] "India"  "Japan"  "Russia" "China"  "USA"   

[[4]]
[1] 95

[[5]]
[1]  50  75  25 100 125

[1] "============================================"
[[1]]
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

[[2]]
[1] 10.25 30.75 20.45 40.85

[[3]]
[1] "Tutorial Gateway"

[[4]]
[1] 95

[[5]]
[1]  50  75  25 100 125

[1] "============================================"
[[1]]
[1] 10.25 30.75 20.45 40.85

[[2]]
[1] "Tutorial Gateway"




<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Manipulating List Elements</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    We can add, delete and update list elements as shown below. We can add and delete elements only at the end of a list. But we can update any element:
                </div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=#076F9A face="Candara" size=4>
                <div align=left>
                    <b>Example:</b>
                </div>
    </font>
</div>

In [16]:
# Create a list containing a vector, a matrix and a list.
list_data <- list(c("Jan", "Feb", "Mar"),
                  matrix(data = c(3, 9, 5, 1, -2, 8), nrow = 2),
                  list("green", 12.3))

# Give names to the elements in the list.
names(list_data) <- c("1st Quarter", "A_Matrix", "A Inner list")

# Add element at the end of the list.
list_data[4] <- "New element"
print(list_data)
cat("=======================================","\n")

# Remove the last element.
list_data[4] <- NULL
print(list_data)
cat("=======================================","\n")

# Print the 4th Element.
print(list_data[4])
cat("=======================================","\n")

# Update the 3rd Element.
list_data[3] <- "updated element"
print(list_data)

$`1st Quarter`
[1] "Jan" "Feb" "Mar"

$A_Matrix
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

$`A Inner list`
$`A Inner list`[[1]]
[1] "green"

$`A Inner list`[[2]]
[1] 12.3


[[4]]
[1] "New element"

$`1st Quarter`
[1] "Jan" "Feb" "Mar"

$A_Matrix
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

$`A Inner list`
$`A Inner list`[[1]]
[1] "green"

$`A Inner list`[[2]]
[1] 12.3


$<NA>
NULL

$`1st Quarter`
[1] "Jan" "Feb" "Mar"

$A_Matrix
     [,1] [,2] [,3]
[1,]    3    5   -2
[2,]    9    1    8

$`A Inner list`
[1] "updated element"




<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Merging Lists</div>
    </font>
</div>

In [17]:
# Create two lists.
list1 <- list(1, 2, 3)
list2 <- list("Sun", "Mon", "Tue")

# Merge the two lists.
merged.list <- c(list1,list2)

# Print the merged list.
print(merged.list)

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] "Sun"

[[5]]
[1] "Mon"

[[6]]
[1] "Tue"




<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>Converting List to Vector</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                   A list can be converted to a vector so that the elements of the vector can be used for further manipulation. All the arithmetic operations on vectors can be applied after the list is converted into vectors. To do this conversion, we use the <mark>unlist() function</mark>. It takes the list as input and produces a vector:
                </div>
    </font>
</div>

In [19]:
# Create lists.
list1 <- list(1:5, 10:15, 1:3)
print(list1)


# Convert the lists to vectors.
v1 <- unlist(list1)

print(v1)

[[1]]
[1] 1 2 3 4 5

[[2]]
[1] 10 11 12 13 14 15

[[3]]
[1] 1 2 3

 [1]  1  2  3  4  5 10 11 12 13 14 15  1  2  3



<div style="line-height:300%;">
    <font color=#9A0909 face="Sriracha" size=6>
                <div align=left>How to access components of a list?</div>
    </font>
</div>

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                   Lists can be accessed in similar fashion to vectors. Integer, logical or character vectors can be used for indexing. Let us consider a list as follows:
                </div>
    </font>
</div>

In [29]:
x <- list(2.5,
          TRUE,
          1:5,
          "Hello",
          matrix(data = 1:4, nrow = 2))

names(x) <- c("int", "log", "vector", "str", "matrix")

print(x)

$int
[1] 2.5

$log
[1] TRUE

$vector
[1] 1 2 3 4 5

$str
[1] "Hello"

$matrix
     [,1] [,2]
[1,]    1    3
[2,]    2    4



In [30]:
x[c(1:2)] # index using integer vector

typeof(x[c(1:2)])
class(x[c(1:2)])

$int
[1] 2.5

$log
[1] TRUE

[1] "list"

[1] "list"

In [31]:
x[-2] # using negative integer to exclude second component

class(x[-2] )

$int
[1] 2.5

$vector
[1] 1 2 3 4 5

$str
[1] "Hello"

$matrix
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[1] "list"

In [32]:
x[c(T, F, F, F, T)] # index using logical vector

class(x[c(T, F, F, F, T)])

$int
[1] 2.5

$matrix
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[1] "list"

In [33]:
x[c("int","matrix")] # index using character vector

class(x[c("int","matrix")])

$int
[1] 2.5

$matrix
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[1] "list"

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                   Indexing with <mark>[</mark> as shown above will give us <mark>Sublist</mark> not the <mark>content inside the component</mark>. To retrieve the content, we need to use <mark>[[</mark>.

<b>However, this approach will allow us to access only a single component at a time.</b>
                </div>
    </font>
</div>

In [35]:
x["int"]

typeof(x["int"])

$int
[1] 2.5

[1] "list"

In [36]:
x[["int"]]

typeof(x[["int"]])

[1] 2.5

[1] "double"

<div style="line-height:200%;">
    <font color=black face="Candara" size=4>
                <div align=left>
                    An alternative to <mark>[[</mark>, which is used often while accessing content of a list is the $ operator.
                </div>
    </font>
</div>

In [39]:
x$vector    # same as x[["vector"]]
typeof(x$vector)
class(x$vector)

[1] 1 2 3 4 5

[1] "integer"

[1] "integer"

In [40]:
x$v

[1] 1 2 3 4 5

In [41]:
 x[["v"]]  

NULL

In [42]:
x$vector[3]

[1] 3

In [43]:
x[["vector"]][3]

[1] 3

In [44]:
x["vector"][3]

$<NA>
NULL
